### PR TITLE
upgrade python version cocoafob to python3

### PR DESCRIPTION
**Pull request by R0uter**

### CODE REVIEW

**Comment by glebd** [comment]
Most of the changes are formatting (using 4-space indentation instead of 2-space). Is it something Python 3 requires? Because currently it's impossible to see if there are other significant changes there.

**Comment by R0uter** [comment]
Sry man, its the plugins, I'll remove them. :)

**Comment by R0uter** [comment]
Now the only changes with what python3 needs.

**Review by glebd — APPROVED** [review]

**Comment by glebd** [comment]
Thank you!

**Pull request merged**
